import { QuantityReportData, CostEstimateReportData } from './ReportService';

/**
 * CSV Export Service
 * Property 38: Export supports multiple formats
 * Validates: Requirements 9.3
 */
export interface ICSVExportService {
  exportQuantityReportToCSV(reportData: QuantityReportData): Promise<string>;
  exportCostEstimateReportToCSV(reportData: CostEstimateReportData): Promise<string>;
}

export class CSVExportService implements ICSVExportService {
  /**
   * Export quantity report to CSV format
   */
  async exportQuantityReportToCSV(reportData: QuantityReportData): Promise<string> {
    const lines: string[] = [];

    // Add header information
    lines.push('Quantity Takeoff Report');
    lines.push('');
    lines.push(`Project,${this.escapeCSV(reportData.metadata.projectName)}`);
    lines.push(`Project ID,${reportData.metadata.projectId}`);
    lines.push(`Generated,${reportData.metadata.generatedAt.toISOString()}`);
    if (reportData.metadata.generatedBy) {
      lines.push(`Generated By,${this.escapeCSV(reportData.metadata.generatedBy)}`);
    }
    lines.push('');

    // Add summary
    lines.push('Summary');
    lines.push(`Total Categories,${reportData.summary.totalCategories}`);
    lines.push(`Total Quantities,${reportData.summary.totalQuantities}`);
    lines.push('');

    // Add quantities data
    lines.push('Quantities by Category');
    lines.push(
      'Category,Type,Value,Unit,Waste Factor,Adjusted Value,Calculation Method'
    );

    for (const categoryGroup of reportData.quantitiesByCategory) {
      for (const quantity of categoryGroup.quantities) {
        const row = [
          this.escapeCSV(categoryGroup.category),
          this.escapeCSV(quantity.quantityType),
          quantity.value.toFixed(2),
          this.escapeCSV(quantity.unit),
          (quantity.wasteFactor * 100).toFixed(2) + '%',
          quantity.adjustedValue.toFixed(2),
          this.escapeCSV(quantity.calculationMethod || 'N/A'),
        ];
        lines.push(row.join(','));
      }
    }

    lines.push('');

    // Add category totals
    lines.push('Category Totals');
    lines.push('Category,Total Value');
    for (const categoryGroup of reportData.quantitiesByCategory) {
      lines.push(
        `${this.escapeCSV(categoryGroup.category)},${categoryGroup.totalValue.toFixed(2)}`
      );
    }

    return lines.join('\n');
  }

  /**
   * Export cost estimate report to CSV format
   */
  async exportCostEstimateReportToCSV(reportData: CostEstimateReportData): Promise<string> {
    const lines: string[] = [];

    // Add header information
    lines.push('Cost Estimate Report');
    lines.push('');
    lines.push(`Project,${this.escapeCSV(reportData.metadata.projectName)}`);
    lines.push(`Project ID,${reportData.metadata.projectId}`);
    lines.push(`Generated,${reportData.metadata.generatedAt.toISOString()}`);
    if (reportData.metadata.generatedBy) {
      lines.push(`Generated By,${this.escapeCSV(reportData.metadata.generatedBy)}`);
    }
    lines.push('');

    // Add estimate information
    lines.push('Estimate Information');
    lines.push(`Name,${this.escapeCSV(reportData.estimate.name)}`);
    if (reportData.estimate.description) {
      lines.push(`Description,${this.escapeCSV(reportData.estimate.description)}`);
    }
    lines.push(`Status,${reportData.estimate.status.toUpperCase()}`);
    lines.push(`Version,${reportData.estimate.version}`);
    lines.push('');

    // Add cost summary
    lines.push('Cost Summary');
    lines.push(`Direct Costs,$${reportData.totals.directCosts.toFixed(2)}`);
    lines.push(`Indirect Costs,$${reportData.totals.indirectCosts.toFixed(2)}`);
    lines.push(`Contingency,$${reportData.totals.contingency.toFixed(2)}`);
    lines.push(`Overhead,$${reportData.totals.overhead.toFixed(2)}`);
    lines.push(`Profit,$${reportData.totals.profit.toFixed(2)}`);
    lines.push(`TOTAL COST,$${reportData.totals.totalCost.toFixed(2)}`);
    lines.push('');

    // Add cost breakdown by CSI code
    lines.push('Cost Breakdown by CSI Division');
    lines.push(
      'CSI Code,Division,Description,Quantity,Unit,Unit Cost,Adj. Unit Cost,Total Cost'
    );

    for (const csiGroup of reportData.costBreakdown.byCSICode) {
      // Add group header
      lines.push(
        `${this.escapeCSV(csiGroup.csiCode)},${this.escapeCSV(csiGroup.description)},,,,,`
      );

      // Add items
      for (const item of csiGroup.items) {
        const row = [
          '', // Empty CSI code for items
          '', // Empty division for items
          this.escapeCSV(item.description),
          item.quantity.toFixed(2),
          this.escapeCSV(item.unit),
          `$${item.unitCost.toFixed(2)}`,
          `$${item.adjustedUnitCost.toFixed(2)}`,
          `$${item.adjustedTotalCost.toFixed(2)}`,
        ];
        lines.push(row.join(','));
      }

      // Add subtotal
      lines.push(`,,,,,,Subtotal,$${csiGroup.subtotal.toFixed(2)}`);
    }

    lines.push('');

    // Add cost breakdown by category
    lines.push('Cost Breakdown by Category');
    lines.push('Category,Description,Quantity,Unit,Unit Cost,Adj. Unit Cost,Total Cost');

    for (const categoryGroup of reportData.costBreakdown.byCategory) {
      // Add group header
      lines.push(`${this.escapeCSV(categoryGroup.category)},,,,,`);

      // Add items
      for (const item of categoryGroup.items) {
        const row = [
          '', // Empty category for items
          this.escapeCSV(item.description),
          item.quantity.toFixed(2),
          this.escapeCSV(item.unit),
          `$${item.unitCost.toFixed(2)}`,
          `$${item.adjustedUnitCost.toFixed(2)}`,
          `$${item.adjustedTotalCost.toFixed(2)}`,
        ];
        lines.push(row.join(','));
      }

      // Add subtotal
      lines.push(`,,,,,Subtotal,$${categoryGroup.subtotal.toFixed(2)}`);
    }

    lines.push('');

    // Add assumptions
    lines.push('Assumptions');
    reportData.assumptions.forEach((assumption, index) => {
      lines.push(`${index + 1},${this.escapeCSV(assumption)}`);
    });

    lines.push('');

    // Add exclusions
    lines.push('Exclusions');
    reportData.exclusions.forEach((exclusion, index) => {
      lines.push(`${index + 1},${this.escapeCSV(exclusion)}`);
    });

    return lines.join('\n');
  }

  /**
   * Escape CSV values to handle commas, quotes, and newlines
   */
  private escapeCSV(value: string): string {
    if (!value) return '';

    // If value contains comma, quote, or newline, wrap in quotes and escape quotes
    if (value.includes(',') || value.includes('"') || value.includes('\n')) {
      return `"${value.replace(/"/g, '""')}"`;
    }

    return value;
  }
}
