import ExcelJS from 'exceljs';
import { QuantityReportData, CostEstimateReportData } from './ReportService';

/**
 * Excel Export Service
 * Property 38: Export supports multiple formats
 * Validates: Requirements 9.3, 9.5
 */
export interface IExcelExportService {
  exportQuantityReportToExcel(reportData: QuantityReportData): Promise<Buffer>;
  exportCostEstimateReportToExcel(reportData: CostEstimateReportData): Promise<Buffer>;
}

export class ExcelExportService implements IExcelExportService {
  /**
   * Export quantity report to Excel format with formulas and formatting
   */
  async exportQuantityReportToExcel(reportData: QuantityReportData): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'ConstructAI';
    workbook.created = new Date();

    // Create summary sheet
    const summarySheet = workbook.addWorksheet('Summary');
    this.addQuantitySummarySheet(summarySheet, reportData);

    // Create detailed quantities sheet
    const detailSheet = workbook.addWorksheet('Quantities');
    this.addQuantityDetailSheet(detailSheet, reportData);

    // Generate buffer
    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }

  /**
   * Export cost estimate report to Excel format with formulas and formatting
   */
  async exportCostEstimateReportToExcel(reportData: CostEstimateReportData): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'ConstructAI';
    workbook.created = new Date();

    // Create summary sheet
    const summarySheet = workbook.addWorksheet('Summary');
    this.addCostSummarySheet(summarySheet, reportData);

    // Create cost breakdown by CSI sheet
    const csiSheet = workbook.addWorksheet('Cost by CSI');
    this.addCostByCSISheet(csiSheet, reportData);

    // Create cost breakdown by category sheet
    const categorySheet = workbook.addWorksheet('Cost by Category');
    this.addCostByCategorySheet(categorySheet, reportData);

    // Generate buffer
    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }

  /**
   * Add quantity summary sheet
   */
  private addQuantitySummarySheet(sheet: ExcelJS.Worksheet, reportData: QuantityReportData) {
    // Title
    sheet.mergeCells('A1:D1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = 'Quantity Takeoff Report';
    titleCell.font = { size: 16, bold: true };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };

    // Project information
    sheet.getCell('A3').value = 'Project:';
    sheet.getCell('B3').value = reportData.metadata.projectName;
    sheet.getCell('A4').value = 'Project ID:';
    sheet.getCell('B4').value = reportData.metadata.projectId;
    sheet.getCell('A5').value = 'Generated:';
    sheet.getCell('B5').value = reportData.metadata.generatedAt.toLocaleString();
    if (reportData.metadata.generatedBy) {
      sheet.getCell('A6').value = 'Generated By:';
      sheet.getCell('B6').value = reportData.metadata.generatedBy;
    }

    // Summary statistics
    let currentRow = 8;
    sheet.getCell(`A${currentRow}`).value = 'Summary';
    sheet.getCell(`A${currentRow}`).font = { size: 14, bold: true };
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Total Categories:';
    sheet.getCell(`B${currentRow}`).value = reportData.summary.totalCategories;
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Total Quantities:';
    sheet.getCell(`B${currentRow}`).value = reportData.summary.totalQuantities;
    currentRow += 2;

    // Category summary table
    sheet.getCell(`A${currentRow}`).value = 'Category';
    sheet.getCell(`B${currentRow}`).value = 'Quantity Count';
    sheet.getCell(`C${currentRow}`).value = 'Total Value';
    sheet.getRow(currentRow).font = { bold: true };
    sheet.getRow(currentRow).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFD3D3D3' },
    };
    currentRow += 1;

    const startRow = currentRow;
    for (const categoryGroup of reportData.quantitiesByCategory) {
      sheet.getCell(`A${currentRow}`).value = categoryGroup.category;
      sheet.getCell(`B${currentRow}`).value = categoryGroup.quantities.length;
      sheet.getCell(`C${currentRow}`).value = categoryGroup.totalValue;
      sheet.getCell(`C${currentRow}`).numFmt = '#,##0.00';
      currentRow += 1;
    }

    // Total row with formula
    sheet.getCell(`A${currentRow}`).value = 'TOTAL';
    sheet.getCell(`A${currentRow}`).font = { bold: true };
    sheet.getCell(`B${currentRow}`).value = {
      formula: `SUM(B${startRow}:B${currentRow - 1})`,
    };
    sheet.getCell(`B${currentRow}`).font = { bold: true };
    sheet.getCell(`C${currentRow}`).value = {
      formula: `SUM(C${startRow}:C${currentRow - 1})`,
    };
    sheet.getCell(`C${currentRow}`).numFmt = '#,##0.00';
    sheet.getCell(`C${currentRow}`).font = { bold: true };

    // Set column widths
    sheet.getColumn('A').width = 30;
    sheet.getColumn('B').width = 20;
    sheet.getColumn('C').width = 20;
    sheet.getColumn('D').width = 20;
  }

  /**
   * Add quantity detail sheet
   */
  private addQuantityDetailSheet(sheet: ExcelJS.Worksheet, reportData: QuantityReportData) {
    // Header row
    const headerRow = sheet.getRow(1);
    headerRow.values = [
      'Category',
      'Type',
      'Value',
      'Unit',
      'Waste Factor',
      'Adjusted Value',
      'Calculation Method',
    ];
    headerRow.font = { bold: true };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFD3D3D3' },
    };

    let currentRow = 2;

    // Add data rows
    for (const categoryGroup of reportData.quantitiesByCategory) {
      for (const quantity of categoryGroup.quantities) {
        const row = sheet.getRow(currentRow);
        row.values = [
          categoryGroup.category,
          quantity.quantityType,
          quantity.value,
          quantity.unit,
          quantity.wasteFactor,
          quantity.adjustedValue,
          quantity.calculationMethod || 'N/A',
        ];

        // Format numbers
        sheet.getCell(`C${currentRow}`).numFmt = '#,##0.00';
        sheet.getCell(`E${currentRow}`).numFmt = '0.00%';
        sheet.getCell(`F${currentRow}`).numFmt = '#,##0.00';

        currentRow += 1;
      }
    }

    // Set column widths
    sheet.getColumn('A').width = 25;
    sheet.getColumn('B').width = 15;
    sheet.getColumn('C').width = 15;
    sheet.getColumn('D').width = 10;
    sheet.getColumn('E').width = 15;
    sheet.getColumn('F').width = 15;
    sheet.getColumn('G').width = 25;

    // Add filters
    sheet.autoFilter = {
      from: 'A1',
      to: `G${currentRow - 1}`,
    };

    // Freeze header row
    sheet.views = [{ state: 'frozen', ySplit: 1 }];
  }

  /**
   * Add cost summary sheet
   */
  private addCostSummarySheet(sheet: ExcelJS.Worksheet, reportData: CostEstimateReportData) {
    // Title
    sheet.mergeCells('A1:D1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = 'Cost Estimate Report';
    titleCell.font = { size: 16, bold: true };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };

    // Project information
    sheet.getCell('A3').value = 'Project:';
    sheet.getCell('B3').value = reportData.metadata.projectName;
    sheet.getCell('A4').value = 'Project ID:';
    sheet.getCell('B4').value = reportData.metadata.projectId;
    sheet.getCell('A5').value = 'Generated:';
    sheet.getCell('B5').value = reportData.metadata.generatedAt.toLocaleString();
    if (reportData.metadata.generatedBy) {
      sheet.getCell('A6').value = 'Generated By:';
      sheet.getCell('B6').value = reportData.metadata.generatedBy;
    }

    // Estimate information
    let currentRow = 8;
    sheet.getCell(`A${currentRow}`).value = 'Estimate Information';
    sheet.getCell(`A${currentRow}`).font = { size: 14, bold: true };
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Name:';
    sheet.getCell(`B${currentRow}`).value = reportData.estimate.name;
    currentRow += 1;

    if (reportData.estimate.description) {
      sheet.getCell(`A${currentRow}`).value = 'Description:';
      sheet.getCell(`B${currentRow}`).value = reportData.estimate.description;
      currentRow += 1;
    }

    sheet.getCell(`A${currentRow}`).value = 'Status:';
    sheet.getCell(`B${currentRow}`).value = reportData.estimate.status.toUpperCase();
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Version:';
    sheet.getCell(`B${currentRow}`).value = reportData.estimate.version;
    currentRow += 2;

    // Cost summary
    sheet.getCell(`A${currentRow}`).value = 'Cost Summary';
    sheet.getCell(`A${currentRow}`).font = { size: 14, bold: true };
    currentRow += 1;

    const totals = reportData.totals;
    const summaryStartRow = currentRow;

    sheet.getCell(`A${currentRow}`).value = 'Direct Costs';
    sheet.getCell(`B${currentRow}`).value = totals.directCosts;
    sheet.getCell(`B${currentRow}`).numFmt = '$#,##0.00';
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Indirect Costs';
    sheet.getCell(`B${currentRow}`).value = totals.indirectCosts;
    sheet.getCell(`B${currentRow}`).numFmt = '$#,##0.00';
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Contingency';
    sheet.getCell(`B${currentRow}`).value = totals.contingency;
    sheet.getCell(`B${currentRow}`).numFmt = '$#,##0.00';
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Overhead';
    sheet.getCell(`B${currentRow}`).value = totals.overhead;
    sheet.getCell(`B${currentRow}`).numFmt = '$#,##0.00';
    currentRow += 1;

    sheet.getCell(`A${currentRow}`).value = 'Profit';
    sheet.getCell(`B${currentRow}`).value = totals.profit;
    sheet.getCell(`B${currentRow}`).numFmt = '$#,##0.00';
    currentRow += 1;

    // Total with formula
    sheet.getCell(`A${currentRow}`).value = 'TOTAL COST';
    sheet.getCell(`A${currentRow}`).font = { size: 12, bold: true };
    sheet.getCell(`B${currentRow}`).value = {
      formula: `SUM(B${summaryStartRow}:B${currentRow - 1})`,
    };
    sheet.getCell(`B${currentRow}`).numFmt = '$#,##0.00';
    sheet.getCell(`B${currentRow}`).font = { size: 12, bold: true };
    sheet.getCell(`B${currentRow}`).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFFEB3B' },
    };

    currentRow += 2;

    // Assumptions
    sheet.getCell(`A${currentRow}`).value = 'Assumptions';
    sheet.getCell(`A${currentRow}`).font = { size: 12, bold: true };
    currentRow += 1;

    reportData.assumptions.forEach((assumption, index) => {
      sheet.getCell(`A${currentRow}`).value = `${index + 1}. ${assumption}`;
      currentRow += 1;
    });

    currentRow += 1;

    // Exclusions
    sheet.getCell(`A${currentRow}`).value = 'Exclusions';
    sheet.getCell(`A${currentRow}`).font = { size: 12, bold: true };
    currentRow += 1;

    reportData.exclusions.forEach((exclusion, index) => {
      sheet.getCell(`A${currentRow}`).value = `${index + 1}. ${exclusion}`;
      currentRow += 1;
    });

    // Set column widths
    sheet.getColumn('A').width = 30;
    sheet.getColumn('B').width = 20;
    sheet.getColumn('C').width = 20;
    sheet.getColumn('D').width = 20;
  }

  /**
   * Add cost by CSI sheet
   */
  private addCostByCSISheet(sheet: ExcelJS.Worksheet, reportData: CostEstimateReportData) {
    // Header row
    const headerRow = sheet.getRow(1);
    headerRow.values = [
      'CSI Code',
      'Division',
      'Description',
      'Quantity',
      'Unit',
      'Unit Cost',
      'Adj. Unit Cost',
      'Total Cost',
    ];
    headerRow.font = { bold: true };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFD3D3D3' },
    };

    let currentRow = 2;

    // Add data rows grouped by CSI code
    for (const csiGroup of reportData.costBreakdown.byCSICode) {
      // Add group header
      const groupHeaderRow = sheet.getRow(currentRow);
      groupHeaderRow.getCell(1).value = csiGroup.csiCode;
      groupHeaderRow.getCell(2).value = csiGroup.description;
      groupHeaderRow.font = { bold: true };
      groupHeaderRow.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFE0E0E0' },
      };
      currentRow += 1;

      const groupStartRow = currentRow;

      // Add items
      for (const item of csiGroup.items) {
        const row = sheet.getRow(currentRow);
        row.values = [
          '', // Empty CSI code column for items
          '', // Empty division column for items
          item.description,
          item.quantity,
          item.unit,
          item.unitCost,
          item.adjustedUnitCost,
          item.adjustedTotalCost,
        ];

        // Format numbers
        sheet.getCell(`D${currentRow}`).numFmt = '#,##0.00';
        sheet.getCell(`F${currentRow}`).numFmt = '$#,##0.00';
        sheet.getCell(`G${currentRow}`).numFmt = '$#,##0.00';
        sheet.getCell(`H${currentRow}`).numFmt = '$#,##0.00';

        currentRow += 1;
      }

      // Add subtotal row with formula
      const subtotalRow = sheet.getRow(currentRow);
      subtotalRow.getCell(7).value = 'Subtotal:';
      subtotalRow.getCell(7).font = { bold: true };
      subtotalRow.getCell(7).alignment = { horizontal: 'right' };
      subtotalRow.getCell(8).value = {
        formula: `SUM(H${groupStartRow}:H${currentRow - 1})`,
      };
      subtotalRow.getCell(8).numFmt = '$#,##0.00';
      subtotalRow.getCell(8).font = { bold: true };
      currentRow += 1;
    }

    // Set column widths
    sheet.getColumn('A').width = 12;
    sheet.getColumn('B').width = 30;
    sheet.getColumn('C').width = 35;
    sheet.getColumn('D').width = 12;
    sheet.getColumn('E').width = 10;
    sheet.getColumn('F').width = 15;
    sheet.getColumn('G').width = 15;
    sheet.getColumn('H').width = 15;

    // Freeze header row
    sheet.views = [{ state: 'frozen', ySplit: 1 }];
  }

  /**
   * Add cost by category sheet
   */
  private addCostByCategorySheet(sheet: ExcelJS.Worksheet, reportData: CostEstimateReportData) {
    // Header row
    const headerRow = sheet.getRow(1);
    headerRow.values = [
      'Category',
      'Description',
      'Quantity',
      'Unit',
      'Unit Cost',
      'Adj. Unit Cost',
      'Total Cost',
    ];
    headerRow.font = { bold: true };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFD3D3D3' },
    };

    let currentRow = 2;

    // Add data rows grouped by category
    for (const categoryGroup of reportData.costBreakdown.byCategory) {
      // Add group header
      const groupHeaderRow = sheet.getRow(currentRow);
      groupHeaderRow.getCell(1).value = categoryGroup.category;
      groupHeaderRow.font = { bold: true };
      groupHeaderRow.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFE0E0E0' },
      };
      currentRow += 1;

      const groupStartRow = currentRow;

      // Add items
      for (const item of categoryGroup.items) {
        const row = sheet.getRow(currentRow);
        row.values = [
          '', // Empty category column for items
          item.description,
          item.quantity,
          item.unit,
          item.unitCost,
          item.adjustedUnitCost,
          item.adjustedTotalCost,
        ];

        // Format numbers
        sheet.getCell(`C${currentRow}`).numFmt = '#,##0.00';
        sheet.getCell(`E${currentRow}`).numFmt = '$#,##0.00';
        sheet.getCell(`F${currentRow}`).numFmt = '$#,##0.00';
        sheet.getCell(`G${currentRow}`).numFmt = '$#,##0.00';

        currentRow += 1;
      }

      // Add subtotal row with formula
      const subtotalRow = sheet.getRow(currentRow);
      subtotalRow.getCell(6).value = 'Subtotal:';
      subtotalRow.getCell(6).font = { bold: true };
      subtotalRow.getCell(6).alignment = { horizontal: 'right' };
      subtotalRow.getCell(7).value = {
        formula: `SUM(G${groupStartRow}:G${currentRow - 1})`,
      };
      subtotalRow.getCell(7).numFmt = '$#,##0.00';
      subtotalRow.getCell(7).font = { bold: true };
      currentRow += 1;
    }

    // Set column widths
    sheet.getColumn('A').width = 25;
    sheet.getColumn('B').width = 35;
    sheet.getColumn('C').width = 12;
    sheet.getColumn('D').width = 10;
    sheet.getColumn('E').width = 15;
    sheet.getColumn('F').width = 15;
    sheet.getColumn('G').width = 15;

    // Freeze header row
    sheet.views = [{ state: 'frozen', ySplit: 1 }];
  }
}
